### ISSUE TITLE
Failure to install with recent node versions

### ISSUE THREAD

**Issue by jeluard** [dinchak/node-monome-grid#2]
When trying to install `node-monome-grid` with a recent `node` (5.1.0) I get a bunch of errors compiling `uvrun`. Apparently there was a change in the C++ layer.

I am not sure how best to address this.

**Comment by dinchak** [comment]
This should be fixed now in the latest version (0.0.6 on NPM).  Let me know how it goes!

**Comment by jeluard** [comment]
Thanks, looks like that fixed it!
